### PR TITLE
CV-220127 Implement 'download the app' banner for AMP pages

### PR DESCRIPTION
**Pull request by palamarchukser**
added rules for 'amp-script' tag
https://amp.dev/documentation/components/amp-script/

merge on green

### CODE REVIEW

**Comment by umpirsky** [comment]
Can you please push same to https://github.com/Lullabot/amp-library? We plan to go back to vendor. @echosa What keeps us from using vendor directly?

**Comment by alexschastny** [comment]
I'm not really involved in this but the changes seem reasonable

**Review by alexschastny — APPROVED** [review]

**Comment by palamarchukser** [comment]
> https://github.com/Lullabot/amp-library

who can I ask for access to https://github.com/Lullabot/amp-library
Which branch should I merge this changes?

**Comment by palamarchukser** [comment]
> Can you please push same to https://github.com/Lullabot/amp-library? We plan to go back to vendor. @echosa What keeps us from using vendor directly?

who can I ask for access to https://github.com/Lullabot/amp-library
Which branch should I merge this changes?

**Comment by umpirsky** [comment]
> > Can you please push same to https://github.com/Lullabot/amp-library? We plan to go back to vendor. @echosa What keeps us from using vendor directly?
> 
> who can I ask for access to https://github.com/Lullabot/amp-library

It's a public repo, just submit PR.

**Comment by echosa** [comment]
> What keeps us from using vendor directly?

It is unmaintained, and attempts to reach out and have previous PRs merged have not worked.

**Comment by umpirsky** [comment]
Oh, in deed. Pity.

**Pull request merged**
